#
# ▒█▀▀█ █░░█ █▀▀▄ █▀▀█ ░▀░ █▀▀▄ ▀▀█▀▀ █▀▀ █░░ █▀▀ █▀▀█ █▀▀█ █▀▀█ ▀▀█▀▀
# ▒█░░░ █░░█ █▀▀▄ █░░█ ▀█▀ █░░█ ░▒█░░ █▀▀ █░░ █▀▀ █░░█ █░░█ █▄▄▀ ░░█░░
# ▒█▄▄█ ░▀▀▀ ▀▀▀░ ▀▀▀▀ ▀▀▀ ▀▀▀░ ░▒█░░ ▀▀▀ ▀▀▀ ▀▀▀ █▀▀▀ ▀▀▀▀ ▀░▀▀ ░░▀░░
#                               v2.0.0
#                         by camper_crafting
#

# Main settings of plugin
locale: en # This plugin has Russian (ru) and English (en) languages
update_check: true
message_prefix: "&#6000FF&lC&#5E0AFF&lu&#5C14FF&lb&#591FFF&lo&#5729FF&li&#5533FF&ld&#533DFF&lT&#5048FF&le&#4E52FF&ll&#4C5CFF&le&#4A66FF&lp&#4771FF&lo&#457BFF&lr&#4385FF&lt&r &7|&r "
general_sound: ENTITY_FISHING_BOBBER_THROW

# Home settings
home_sound: ENTITY_ENDERMAN_TELEPORT

# Warp settings
warp_sound: ENTITY_ENDERMAN_TELEPORT

# RTP settings
rtp_sound: ENTITY_ENDERMAN_TELEPORT
teleport_radius: 1000 # RTP radius

# Tpa settings
tpa_sound: ENTITY_ENDERMAN_TELEPORT

# Other commands settings
cooldowns:
  call: 30      # 30 seconds
  tpa: 30       # 30 seconds
  home: 5       # 5 seconds
  rtp: 60       # 60 seconds
  warp: 10      # 10 seconds
  sethome: 5    # 5 seconds
  setwarp: 5    # 5 seconds